/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.festu.ivankuznetsov.samples.java;

import java.util.ArrayList;
import java.util.List;

public class App {
    public static void main(String[] args) {
        ArrayList<Integer> list = new ArrayList<>(List.of(1, 2, 3, 4, 5));
    }
}
